FROM node:12.18.0

ENV TIMEZONE=${timezone:-"Asia/Shanghai"}
RUN ln -sf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
  && echo "${TIMEZONE}" > /etc/timezone

RUN npm install

COPY ./ /data/my-node-server
WORKDIR /data/my-node-server

CMD npm run start:docker:local

EXPOSE 8080